"""Structured bibliographic reference, rendered in IEEE style."""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, fields
from datetime import date
from typing import Any

BOOK = "book"
JOURNAL_ARTICLE = "journal_article"
STANDARD = "standard"
TECHNICAL_REPORT = "technical_report"
OFFICIAL_WEB = "official_web"
COURSE_MATERIAL = "course_material"
SOURCE_TYPES = (BOOK, JOURNAL_ARTICLE, STANDARD, TECHNICAL_REPORT, OFFICIAL_WEB, COURSE_MATERIAL)

# Identifiers that belong to exactly one source type; elsewhere they signal a wrong type.
TYPE_SPECIFIC_FIELDS = {
    "journal": JOURNAL_ARTICLE,
    "standard_number": STANDARD,
    "report_number": TECHNICAL_REPORT,
}

EARLIEST_YEAR = 1600
MAX_LISTED_AUTHORS = 6  # IEEE lists up to six names, then uses "et al."
DOI_PATTERN = re.compile(r"^10\.\d{4,9}/\S+$")
ISO_DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")
CITATION_NUMBER_PATTERN = re.compile(r"^\s*\[\d+\]")
URL_PREFIXES = ("https://", "http://")
PAGE_RANGE_MARKS = ("-", "–", ",")  # hyphen, en dash, comma
IEEE_MONTHS = (
    "Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.",
    "Jul.", "Aug.", "Sept.", "Oct.", "Nov.", "Dec.",
)


@dataclass(frozen=True)
class ReferenceSpec:
    """One source that verifies a formula, stored as structured bibliographic fields.

    Fill in only metadata read from the source itself or from a reliable bibliographic
    record. Leave anything that could not be verified as ``None``. The IEEE citation is
    always generated by :meth:`format_ieee`; never store a pre-formatted citation or a
    citation number.

    Attributes:
        source_type: One of ``SOURCE_TYPES``: ``"book"``, ``"journal_article"``,
            ``"standard"``, ``"technical_report"``, ``"official_web"``,
            ``"course_material"``.
        title: Title exactly as given by the source.
        authors: Personal authors in IEEE name form (initials then surname), e.g.
            ``("J. D. Anderson",)``. Empty when the source names none.
        organization: Corporate author, issuing body, or institution.
        year: Year of publication (for web pages, the stated last-updated year).
        edition: Edition as an ordinal without "ed.", e.g. ``"6th"``.
        publisher: Publisher name.
        place: Place of publication, e.g. ``"New York, NY, USA"``.
        journal: Journal or conference proceedings name (journal articles only).
        volume: Volume number.
        issue: Issue number.
        pages: Page or page range in the journal, e.g. ``"100-110"``.
        standard_number: Standard designation, e.g. ``"ISO 2533:1975"`` (standards only).
        report_number: Report number as printed on the report (technical reports only).
        locator: Where in the source the formula is verified, e.g. ``"sec. 3.4"``.
        doi: DOI without a resolver prefix, e.g. ``"10.1000/xyz123"``.
        url: Stable URL of the source.
        accessed: Date the URL was accessed, as ``"YYYY-MM-DD"``.
    """

    source_type: str
    title: str
    authors: tuple[str, ...] = ()
    organization: str | None = None
    year: int | None = None
    edition: str | None = None
    publisher: str | None = None
    place: str | None = None
    journal: str | None = None
    volume: str | None = None
    issue: str | None = None
    pages: str | None = None
    standard_number: str | None = None
    report_number: str | None = None
    locator: str | None = None
    doi: str | None = None
    url: str | None = None
    accessed: str | None = None

    def __post_init__(self) -> None:
        self.validate()

    def validate(self) -> None:
        """Check the structural requirements for this source type.

        Raises:
            ValueError: If the reference is malformed or lacks identifying metadata.
        """
        problems = self._problems()
        if problems:
            raise ValueError(
                f"Invalid {self.source_type!r} reference {self.title!r}: {'; '.join(problems)}."
            )

    def format_ieee(self) -> str:
        """Return the citation in IEEE style, without a citation number."""
        lead = _join_names(self.authors) if self.authors else self.organization
        issuer = self.organization if self.authors else None
        year = str(self.year) if self.year is not None else None
        doi = f"doi: {self.doi}" if self.doi else None

        if self.source_type == BOOK:
            edition = f", {self.edition} ed." if self.edition else "."
            publisher = f"{self.place}: {self.publisher}" if self.place else self.publisher
            text = f"{lead}, {self.title}{edition} {_clause(publisher, year, self.locator, doi)}"
        elif self.source_type == STANDARD:
            details = _clause(self.organization, self.place, year, self.locator, doi)
            text = f"{self.standard_number}, {self.title}. {details}"
        elif self.source_type == JOURNAL_ARTICLE:
            text = _quoted_title(
                lead,
                self.title,
                self.journal,
                f"vol. {self.volume}" if self.volume else None,
                f"no. {self.issue}" if self.issue else None,
                _pages(self.pages),
                year,
                self.locator,
                doi,
            )
        else:
            text = _quoted_title(
                lead, self.title, issuer, self.place, self.report_number, year, self.locator, doi
            )

        if self.url:
            accessed = f"Accessed: {_ieee_date(self.accessed)}. " if self.accessed else ""
            text = f"{text} {accessed}[Online]. Available: {self.url}"
        return text

    def to_dict(self) -> dict[str, Any]:
        """Return the structured fields as JSON-serializable data."""
        data = asdict(self)
        data["authors"] = list(self.authors)
        return data

    def _problems(self) -> list[str]:
        if self.source_type not in SOURCE_TYPES:
            return [f"source_type must be one of {SOURCE_TYPES}"]

        problems = []
        if not isinstance(self.authors, tuple) or not all(
            isinstance(name, str) and name.strip() for name in self.authors
        ):
            problems.append(
                'authors must be a tuple of non-empty strings, e.g. ("J. D. Anderson",)'
            )
        for spec_field in fields(self):
            value = getattr(self, spec_field.name)
            if spec_field.name in ("authors", "year") or value is None:
                continue
            if not isinstance(value, str) or not value.strip():
                optional = "" if spec_field.name == "title" else " or None"
                problems.append(f"{spec_field.name} must be a non-empty string{optional}")
        if self.year is not None and (
            isinstance(self.year, bool)
            or not isinstance(self.year, int)
            or not EARLIEST_YEAR <= self.year <= date.today().year + 1
        ):
            problems.append(f"year must be an int between {EARLIEST_YEAR} and next year")
        if problems:
            return problems  # The checks below assume well-typed fields.

        if CITATION_NUMBER_PATTERN.match(self.title):
            problems.append("title must not include citation numbering such as [1]")
        if self.doi is not None and not DOI_PATTERN.match(self.doi):
            problems.append("doi must look like 10.xxxx/yyyy, without a https://doi.org/ prefix")
        if self.url is not None and (
            not self.url.startswith(URL_PREFIXES) or any(c.isspace() for c in self.url)
        ):
            problems.append("url must be an http(s) URL without spaces")
        if self.accessed is not None:
            problems.extend(_accessed_problems(self.accessed, has_url=self.url is not None))
        for name, owner in TYPE_SPECIFIC_FIELDS.items():
            if getattr(self, name) is not None and self.source_type != owner:
                problems.append(f"{name} is only used for {owner} references")
        if self.source_type == STANDARD and self.authors:
            problems.append("standards are cited by organization, not personal authors")

        for label, present in self._required():
            if not present:
                problems.append(f"{label} is required")
        return problems

    def _required(self) -> tuple[tuple[str, bool], ...]:
        """Return (label, present) pairs for the identifying fields this type needs."""
        has_creator = bool(self.authors) or self.organization is not None
        creator = ("author(s) or organization", has_creator)
        if self.source_type == BOOK:
            return (
                creator,
                ("publisher", self.publisher is not None),
                ("year", self.year is not None),
            )
        if self.source_type == JOURNAL_ARTICLE:
            return (
                ("author(s)", bool(self.authors)),
                ("journal", self.journal is not None),
                ("year", self.year is not None),
            )
        if self.source_type == STANDARD:
            return (
                ("standard_number", self.standard_number is not None),
                ("organization", self.organization is not None),
            )
        if self.source_type == OFFICIAL_WEB:
            return (
                ("organization", self.organization is not None),
                ("url", self.url is not None),
                ("accessed", self.accessed is not None),
            )
        return (creator,)  # technical_report, course_material


def _accessed_problems(accessed: str, has_url: bool) -> list[str]:
    if not has_url:
        return ["accessed is only meaningful together with url"]
    if not ISO_DATE_PATTERN.match(accessed):
        return ["accessed must be a YYYY-MM-DD date"]
    try:
        accessed_date = date.fromisoformat(accessed)
    except ValueError:
        return ["accessed must be a real calendar date"]
    if accessed_date > date.today():
        return ["accessed must not be in the future"]
    return []


def _join_names(names: tuple[str, ...]) -> str:
    if len(names) > MAX_LISTED_AUTHORS:
        return f"{names[0]} et al."
    if len(names) <= 2:
        return " and ".join(names)
    return f"{', '.join(names[:-1])}, and {names[-1]}"


def _clause(*parts: str | None) -> str:
    """Join the present parts with commas and end the clause with a period."""
    text = ", ".join(part for part in parts if part)
    return text if not text or text.endswith(".") else f"{text}."


def _quoted_title(lead: str | None, title: str, *details: str | None) -> str:
    clause = _clause(*details)
    return f'{lead}, "{title}," {clause}' if clause else f'{lead}, "{title}."'


def _pages(pages: str | None) -> str | None:
    if pages is None:
        return None
    prefix = "pp." if any(mark in pages for mark in PAGE_RANGE_MARKS) else "p."
    return f"{prefix} {pages}"


def _ieee_date(iso_date: str) -> str:
    day = date.fromisoformat(iso_date)
    return f"{IEEE_MONTHS[day.month - 1]} {day.day}, {day.year}"
